### ISSUE TITLE
img

### ISSUE THREAD

**Issue by AlexandreSouzaDev** [XANDRAO/Site-Responsivo#1]
![img1](https://user-images.githubusercontent.com/100946873/190887584-aed688ae-7247-474e-b795-a74bee781b88.jpg)
![img2](https://user-images.githubusercontent.com/100946873/190887589-437c713d-7256-4231-b55b-a9c9b61df98e.jpg)
![img3](https://user-images.githubusercontent.com/100946873/190887592-afd5d54a-1036-46c0-bfa4-837706474ffa.jpg)
![img4](https://user-images.githubusercontent.com/100946873/190887601-a108c137-8aec-4b1c-9d17-f186fd2f9915.jpg)
![background](https://user-images.githubusercontent.com/100946873/190887582-cbcda282-963e-4691-8a1b-6146c5a70c6b.jpg)
![logo](https://user-images.githubusercontent.com/100946873/190887662-a9cacfbc-236e-458b-8483-5fbbd5795917.png)
![menu](https://user-images.githubusercontent.com/100946873/190887669-e554e8a3-2faa-45eb-9202-63b9aebfcb15.png)

**Comment by XANDRAO** [comment]
![logo](https://user-images.githubusercontent.com/100946873/190887662-a9cacfbc-236e-458b-8483-5fbbd5795917.png)

**Comment by AlexandreSouzaDev** [comment]
![menu](https://user-images.githubusercontent.com/100946873/190887669-e554e8a3-2faa-45eb-9202-63b9aebfcb15.png)
